parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_sqlite'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        path: '%kernel.project_dir%/var/database.sqlite'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            ContextsUser:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/resources/doctrine/user'
                prefix: Contexts\User
                alias: ContextsUser

            ContextsService:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/resources/doctrine/service'
                prefix: Contexts\Service
                alias: ContextsService

            ContextsCommon:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/resources/doctrine/common'
                prefix: Contexts\Common
                alias: ContextsCommon